/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-call */
import Head from "next/head";
import { SignIn, useUser, SignOutButton } from "@clerk/nextjs";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const leagues = api.league.getAll.useQuery();
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!user.isSignedIn && <SignIn />}
        {!!user.isSignedIn && (
          <div>
            <SignOutButton />
            <h1 className="text-2xl text-white">{hello.data?.greeting}</h1>
            <h2 className="text-xl text-white">Leagues:</h2>
            <ul>
              {leagues.data?.map((league) => (
                <li key={league.id} className="text-white">
                  {league.name}
                </li>
              ))}
            </ul>
          </div>
        )}
      </main>
    </>
  );
}
